spring:
  application:
    name: MM-quiz-RD

  profiles:
    active: dev 
        
  config:
    import: optional:configserver:http://localhost:8071 

spring:
  cloud:
    stream:
      function:
        definition: quizConsumer;quizProducer # Registra qui i tuoi Bean Java
      bindings:
        quizProducer-out-0: # Nome logico standard: <functionName>-out-<index>
          destination: quiz-topic
        quizConsumer-in-0:  # Nome logico standard: <functionName>-in-<index>
          destination: quiz-topic
          group: quiz-group-rd
      kafka:
        binder:
          brokers: localhost:9092 # Deve corrispondere alla porta nel docker-compose

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: refresh
  health:
    circuitbreakers:
      enabled: true
    ratelimiters:
      enabled: true