        
spring:
  application:
    name: Catalogo_RD
    
  config:
    import: optional:configserver:http://localhost:8071 
    
  profiles:
    active: dev

  cloud:
    stream:
      bindings:
        myConsumer-in-0:
          destination: my-topic
          group: consumer
      kafka:
        binder:
          brokers: localhost:9092


#attiva l'end point dell'actuator per il refresh delle propriet� di configurazione
#lette dal server di configurazione
management:
  endpoints:
    web:
      exposure:
        include: refresh